# postgre-db.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-deployment
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.1     
          env:
            - name: POSTGRES_DB
              value: budgy_development
            - name: POSTGRES_USER
              value: Budgy
            - name: POSTGRES_PASSWORD
              value: Budgy
          ports:
            - containerPort: 5432
# budget-app-web.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-app-web
  template:
    metadata:
      labels:
        app: budget-app-web
    spec:
      containers:
        - name: budget-app-web
          image: jarvis99/budget-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_USER
              value: "Budgy"
            - name: DB_PASSWORD
              value: "Budgy"
            - name: DB_NAME
              value: "budgy_development"
---
apiVersion: v1
kind: Service
metadata:
  name: budget-app-web-service
spec:
  selector:
    app: budget-app-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budget-app-web-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: budget-app-web-service
            port:
              number: 3000
